---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    
    # Group related updates to reduce PR noise
    groups:
      testcontainers:
        patterns:
          - "github.com/testcontainers/testcontainers-go*"
        
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
          
      docker-deps:
        patterns:
          - "github.com/docker/*"
          - "github.com/moby/*"
          - "github.com/containerd/*"
    
    commit-message:
      prefix: chore
      include: scope