---
name: App CD

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

#  push:
#    branches:
#      - main
#
#    paths:
#      - 'cmd/**'
#      - 'internal/**'
#      - go.mod
#      - go.sum
#      - Dockerfile

defaults:
  run:
    shell: bash

jobs:
  cd:
    name: Deploy
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_GH_RUNNER }}
          aws-region: ${{ vars.AWS_REGION }}

      
