---
name: Tests

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

    paths:
      - 'cmd/**'
      - 'internal/**'
      - go.mod
      - go.sum

  push:
    branches-ignore:
      - main

    paths:
      - 'cmd/**'
      - 'internal/**'
      - go.mod
      - go.sum

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
      
      - name: Copy migrations for embed
        run: cp -r migrations/ cmd/api/migrations/

      - name: Run tests
        run: go test -v ./...